using Application.Allcodes.Repositories;
using Dapper;
using DomainAllcode = Domain.Allcodes.Allcode;
using Infrastructure.Persistence.Db;
using AllcodeEntity = Infrastructure.Persistence.Entities.Allcodes.Allcode;
using Infrastructure.Persistence.Querying;
using Microsoft.Extensions.Logging;

namespace Infrastructure.Persistence.Repositories;

public class AllcodeRepository : IAllcodeRepository
{
    private readonly IDbConnectionFactory _connectionFactory;
    private readonly ILogger<AllcodeRepository> _logger;

    public AllcodeRepository(IDbConnectionFactory connectionFactory, ILogger<AllcodeRepository> logger)
    {
        _connectionFactory = connectionFactory;
        _logger = logger;
    }

    public async Task<AllcodeSearchResult> SearchAsync(AllcodeSearchCondition condition, CancellationToken cancellationToken = default)
    {
        try
        {
            var cdName = condition.CdName.Trim();
            var cdValue = condition.CdValue?.Trim() ?? string.Empty;
            var display = condition.Display.Trim();

            IQueryBuilder<AllcodeEntity, object> countQueryBuilder = new QueryBuilder<AllcodeEntity, object>();
            var countSql = countQueryBuilder
                .SelectRaw("COUNT(*)")
                .Where(a => a.CdName == cdName
                    && (cdValue == "" || a.CdValue == cdValue)
                    && a.Display == display)
                .BuildQuery();

            IQueryBuilder<AllcodeEntity, object> dataQueryBuilder = new QueryBuilder<AllcodeEntity, object>();
            var dataSql = dataQueryBuilder
                .SelectRaw("t.Id, t.CdName, t.CdValue, t.text_vn AS TextVn, t.text_en AS TextEn, t.Display")
                .Where(a => a.CdName == cdName
                    && (cdValue == "" || a.CdValue == cdValue)
                    && a.Display == display)
                .OrderBy(a => a.Id)
                .BuildQuery();

            _logger.LogInformation("Search allcode SQL generated by IQueryBuilder: {Sql}", dataSql);
            _logger.LogInformation("Search allcode COUNT SQL generated by IQueryBuilder: {Sql}", countSql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var total = await connection.ExecuteScalarAsync<int>(new CommandDefinition(countSql, cancellationToken: cancellationToken));
            var rows = (await connection.QueryAsync<AllcodeEntity>(new CommandDefinition(dataSql, cancellationToken: cancellationToken))).ToList();

            return new AllcodeSearchResult
            {
                Items = rows.Select(MapToDomain).ToList(),
                Total = total
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "SearchAsync failed for allcode cdName: {CdName}", condition.CdName);
            throw;
        }
    }

    private static DomainAllcode MapToDomain(AllcodeEntity entity)
    {
        return new DomainAllcode
        {
            Id = entity.Id,
            CdName = entity.CdName,
            CdValue = entity.CdValue,
            TextVn = entity.TextVn,
            TextEn = entity.TextEn,
            Display = entity.Display
        };
    }
}
