using Application.Contracts.Repositories;
using Dapper;
using Domain.Contracts;
using Infrastructure.Persistence.Db;
using Infrastructure.Persistence.Entities.Packages;
using Infrastructure.Persistence.Entities.Products;
using Infrastructure.Persistence.Querying;
using Microsoft.Extensions.Logging;
using ContractItemEntity = Infrastructure.Persistence.Entities.Contracts.ContractItem;
using ContractPackageEntity = Infrastructure.Persistence.Entities.Contracts.ContractPackage;

namespace Infrastructure.Persistence.Repositories;

public class ContractRepository : IContractRepository
{
    private readonly IDbConnectionFactory _connectionFactory;
    private readonly ILogger<ContractRepository> _logger;

    public ContractRepository(IDbConnectionFactory connectionFactory, ILogger<ContractRepository> logger)
    {
        _connectionFactory = connectionFactory;
        _logger = logger;
    }

    public async Task<Contract?> GetByIdAsync(long contractId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Contract, object> queryBuilder = new QueryBuilder<Contract, object>();
            var sql = queryBuilder
                .SelectRaw(BuildContractSelectClause())
                .Where(c => c.Id == contractId)
                .BuildQuery();

            _logger.LogInformation("GetById contract SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            return await connection.QueryFirstOrDefaultAsync<Contract>(
                new CommandDefinition(sql, cancellationToken: cancellationToken));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByIdAsync failed for contract id: {Id}", contractId);
            throw;
        }
    }

    public async Task<Contract?> GetByContractNoAsync(string contractNo, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Contract, object> queryBuilder = new QueryBuilder<Contract, object>();
            var sql = queryBuilder
                .SelectRaw(BuildContractSelectClause())
                .Where(c => c.ContractNo == contractNo)
                .BuildQuery();

            _logger.LogInformation("GetByContractNo contract SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            return await connection.QueryFirstOrDefaultAsync<Contract>(
                new CommandDefinition(sql, cancellationToken: cancellationToken));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByContractNoAsync failed for contract no: {ContractNo}", contractNo);
            throw;
        }
    }

    public async Task<long> InsertAsync(Contract contract, CancellationToken cancellationToken = default)
    {
        try
        {
            var sql = BuildInsertContractSql(contract);
            _logger.LogInformation("Insert contract SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            return await connection.ExecuteScalarAsync<long>(new CommandDefinition(sql, cancellationToken: cancellationToken));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertAsync failed for contract no: {ContractNo}", contract.ContractNo);
            throw;
        }
    }

    public async Task<long> InsertExportAggregateAsync(
        Contract contract,
        IReadOnlyCollection<ContractAttachment> attachments,
        IReadOnlyCollection<ContractPackage> packages,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var insertContractSql = BuildInsertContractSql(contract);

            using var connection = _connectionFactory.CreateOpenConnection();
            using var transaction = connection.BeginTransaction();

            try
            {
                var contractId = await connection.ExecuteScalarAsync<long>(
                    new CommandDefinition(insertContractSql, contract, transaction: transaction, cancellationToken: cancellationToken));

                foreach (var attachment in attachments)
                {
                    attachment.ContractId = contractId;
                    var insertAttachmentSql = BuildInsertAttachmentSql(attachment);
                    await connection.ExecuteAsync(
                        new CommandDefinition(insertAttachmentSql, transaction: transaction, cancellationToken: cancellationToken));
                }

                foreach (var package in packages)
                {
                    package.ContractId = contractId;
                    var insertContractPackageSql = BuildInsertContractPackageSql(package);
                    var contractPackageId = await connection.ExecuteScalarAsync<long>(
                        new CommandDefinition(insertContractPackageSql, transaction: transaction, cancellationToken: cancellationToken));

                    var item = new ContractItem
                    {
                        ContractId = contractId,
                        ContractPackageId = contractPackageId,
                        PackageId = package.PackageId,
                        ProductId = package.ProductId,
                        SupplierId = null,
                        Quantity = package.Quantity,
                        ImportPrice = 0,
                        SellPrice = package.SellPrice,
                        TotalImportAmount = 0,
                        TotalSellAmount = package.TotalSellAmount,
                        CreatedBy = package.CreatedBy,
                        CreatedDate = package.CreatedDate
                    };

                    var insertContractItemSql = BuildInsertContractItemSql(item);
                    await connection.ExecuteAsync(
                        new CommandDefinition(insertContractItemSql, transaction: transaction, cancellationToken: cancellationToken));
                }

                transaction.Commit();
                return contractId;
            }
            catch
            {
                transaction.Rollback();
                throw;
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertExportAggregateAsync failed for contract no: {ContractNo}", contract.ContractNo);
            throw;
        }
    }

    public async Task<long> InsertImportAggregateAsync(
        Contract contract,
        IReadOnlyCollection<ContractAttachment> attachments,
        IReadOnlyCollection<ContractItem> items,
        CancellationToken cancellationToken = default)
    {
        try
        {
            var insertContractSql = BuildInsertContractSql(contract);

            using var connection = _connectionFactory.CreateOpenConnection();
            using var transaction = connection.BeginTransaction();

            try
            {
                var contractId = await connection.ExecuteScalarAsync<long>(
                    new CommandDefinition(insertContractSql, contract, transaction: transaction, cancellationToken: cancellationToken));

                foreach (var attachment in attachments)
                {
                    attachment.ContractId = contractId;
                    var insertAttachmentSql = BuildInsertAttachmentSql(attachment);
                    await connection.ExecuteAsync(
                        new CommandDefinition(insertAttachmentSql, transaction: transaction, cancellationToken: cancellationToken));
                }

                foreach (var item in items)
                {
                    item.ContractId = contractId;
                    var insertContractItemSql = BuildInsertContractItemSql(item);
                    await connection.ExecuteAsync(
                        new CommandDefinition(insertContractItemSql, transaction: transaction, cancellationToken: cancellationToken));
                }

                transaction.Commit();
                return contractId;
            }
            catch
            {
                transaction.Rollback();
                throw;
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertImportAggregateAsync failed for contract no: {ContractNo}", contract.ContractNo);
            throw;
        }
    }

    public async Task<long> InsertAttachmentAsync(ContractAttachment attachment, CancellationToken cancellationToken = default)
    {
        try
        {
            var sql = BuildInsertAttachmentSql(attachment) + "\nRETURNING id;";
            _logger.LogInformation("Insert contract attachment SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            return await connection.ExecuteScalarAsync<long>(new CommandDefinition(sql, cancellationToken: cancellationToken));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertAttachmentAsync failed for contract id: {ContractId}", attachment.ContractId);
            throw;
        }
    }

    public async Task<ContractDetailData?> GetDetailAsync(long contractId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Contract, object> contractQueryBuilder = new QueryBuilder<Contract, object>();
            var contractSql = contractQueryBuilder
                .SelectRaw(BuildContractSelectClause())
                .Where(c => c.Id == contractId)
                .BuildQuery();

            _logger.LogInformation("GetDetail contract SQL generated by IQueryBuilder: {Sql}", contractSql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var contract = await connection.QueryFirstOrDefaultAsync<Contract>(
                new CommandDefinition(contractSql, cancellationToken: cancellationToken));
            if (contract is null)
            {
                return null;
            }

            IQueryBuilder<ContractAttachment, object> attachmentQueryBuilder = new QueryBuilder<ContractAttachment, object>();
            var attachmentSql = attachmentQueryBuilder
                .Select(a => new { a.Id, a.ContractId, a.FileName, a.FileUrl, a.FileExtension, a.CreatedBy, a.CreatedDate, a.UpdatedBy, a.UpdatedDate })
                .Where(a => a.ContractId == contractId)
                .OrderBy(a => a.Id)
                .BuildQuery();

            _logger.LogInformation("GetDetail contract attachment SQL generated by IQueryBuilder: {Sql}", attachmentSql);

            var attachments = (await connection.QueryAsync<ContractAttachment>(
                new CommandDefinition(attachmentSql, cancellationToken: cancellationToken))).ToList();

            var packages = new List<ContractPackage>();
            var items = new List<ContractItem>();

            if (string.Equals(contract.ContractType, ContractTypes.Export, StringComparison.OrdinalIgnoreCase))
            {
                IQueryBuilder<ContractPackageEntity, object> packageQueryBuilder = new QueryBuilder<ContractPackageEntity, object>();
                var packageSql = packageQueryBuilder
                    .InnerJoin<PackingList>((line, package) => line.PackageId == package.Id, "pkg")
                    .InnerJoin<Product>((line, product) => line.ProductId == product.Id, "p")
                    .LeftJoin<ContractItemEntity>((line, item) => line.Id == item.ContractPackageId, "ci")
                    .SelectRaw("t.Id, t.ContractId, t.PackageId, pkg.PackingListNo AS PackageCode, pkg.PackageName, t.ProductId, p.ProductCode, p.ProductName, pkg.ProductQuantity, t.PackageQuantity, COALESCE(ci.Quantity, pkg.ProductQuantity * t.PackageQuantity) AS Quantity, COALESCE(ci.SellPrice, 0) AS SellPrice, COALESCE(ci.TotalSellAmount, 0) AS TotalSellAmount, pkg.Length, pkg.Width, pkg.Height, t.Note, t.CreatedBy, t.CreatedDate, t.UpdatedBy, t.UpdatedDate")
                    .Where(line => line.ContractId == contractId)
                    .OrderBy(line => line.Id)
                    .BuildQuery();

                _logger.LogInformation("GetDetail export contract package SQL generated by IQueryBuilder: {Sql}", packageSql);

                packages = (await connection.QueryAsync<ContractPackage>(
                    new CommandDefinition(packageSql, cancellationToken: cancellationToken))).ToList();
            }
            else
            {
                IQueryBuilder<ContractItemEntity, object> itemQueryBuilder = new QueryBuilder<ContractItemEntity, object>();
                var itemSql = itemQueryBuilder
                    .InnerJoin<Product>((item, product) => item.ProductId == product.Id, "p")
                    .SelectRaw("t.Id, t.ContractId, t.ContractPackageId, t.PackageId, t.ProductId, p.ProductCode, p.ProductName, t.SupplierId, (SELECT s.PartnerName FROM Partner s WHERE s.Id = t.SupplierId) AS SupplierName, t.Quantity, t.ImportPrice, t.SellPrice, t.TotalImportAmount, t.TotalSellAmount, t.CreatedBy, t.CreatedDate, t.UpdatedBy, t.UpdatedDate")
                    .Where(item => item.ContractId == contractId)
                    .OrderBy(item => item.Id)
                    .BuildQuery();

                _logger.LogInformation("GetDetail import contract item SQL generated by IQueryBuilder: {Sql}", itemSql);

                items = (await connection.QueryAsync<ContractItem>(
                    new CommandDefinition(itemSql, cancellationToken: cancellationToken))).ToList();
            }

            return new ContractDetailData
            {
                Contract = contract,
                Attachments = attachments,
                Packages = packages,
                Items = items
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetDetailAsync failed for contract id: {Id}", contractId);
            throw;
        }
    }

    public async Task<ContractSearchResult> SearchAsync(ContractSearchCondition condition, CancellationToken cancellationToken = default)
    {
        const string whereClause = """
            (@KeywordPattern IS NULL
                OR t.ContractNo ILIKE @KeywordPattern
                OR COALESCE(t.Incoterm, '') ILIKE @KeywordPattern
                OR COALESCE(t.PaymentTerms, '') ILIKE @KeywordPattern
                OR COALESCE(t.ShipmentDatePlan, '') ILIKE @KeywordPattern
                OR COALESCE(t.Note, '') ILIKE @KeywordPattern
                OR COALESCE((SELECT p.PartnerName FROM Partner p WHERE p.Id = t.BuyerId), '') ILIKE @KeywordPattern
                OR COALESCE((SELECT p.PartnerName FROM Partner p WHERE p.Id = t.SupplierId), '') ILIKE @KeywordPattern
                OR COALESCE((SELECT c.ContractNo FROM Contract c WHERE c.Id = t.ImportContractId), '') ILIKE @KeywordPattern)
            --AND (@ContractType IS NULL OR t.ContractType = @ContractType)
            """;

        IQueryBuilder<Contract, object> countQueryBuilder = new QueryBuilder<Contract, object>();
        var countSql = countQueryBuilder
            .SelectRaw("COUNT(*)")
            .WhereRaw(whereClause)
            .BuildQuery();

        IQueryBuilder<Contract, object> dataQueryBuilder = new QueryBuilder<Contract, object>();
        var dataSql = dataQueryBuilder
            .SelectRaw(BuildContractSelectClause())
            .WhereRaw(whereClause)
            .OrderByDescending(c => c.ContractDate)
            .ThenByDescending(c => c.Id)
            .Offset(condition.Offset)
            .Limit(condition.Limit)
            .BuildQuery();

        var parameters = new
        {
            KeywordPattern = string.IsNullOrWhiteSpace(condition.Keyword) ? null : $"%{condition.Keyword.Trim()}%",
            condition.ContractType,
            condition.Offset,
            condition.Limit
        };

        try
        {
            _logger.LogInformation("Search contract SQL generated by IQueryBuilder: {Sql}", dataSql);
            _logger.LogInformation("Search contract COUNT SQL generated by IQueryBuilder: {Sql}", countSql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var total = await connection.ExecuteScalarAsync<int>(new CommandDefinition(countSql, parameters, cancellationToken: cancellationToken));
            var items = (await connection.QueryAsync<Contract>(new CommandDefinition(dataSql, parameters, cancellationToken: cancellationToken))).ToList();

            return new ContractSearchResult
            {
                Items = items,
                Total = total
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "SearchAsync failed for contracts.");
            throw;
        }
    }

    private static string BuildContractSelectClause()
    {
        return "t.Id, t.ContractNo, t.ContractDate, t.ContractType, t.BuyerId, " +
               "(SELECT p.PartnerName FROM Partner p WHERE p.Id = t.BuyerId) AS BuyerName, " +
               "t.SupplierId, (SELECT p.PartnerName FROM Partner p WHERE p.Id = t.SupplierId) AS SupplierName, " +
               "t.ImportContractId, (SELECT c.ContractNo FROM Contract c WHERE c.Id = t.ImportContractId) AS ImportContractNo, " +
               "t.SalesOrderId, t.Incoterm, t.PaymentTerms, t.ShipmentDatePlan, t.Note, t.CreatedBy, t.CreatedDate, t.UpdatedBy, t.UpdatedDate";
    }

    private static string BuildInsertContractSql(Contract contract)
    {
        IQueryBuilder<Contract, object> queryBuilder = new QueryBuilder<Contract, object>();
        return queryBuilder
            .Insert(() => new Contract
            {
                ContractNo = contract.ContractNo,
                ContractDate = contract.ContractDate,
                ContractType = contract.ContractType,
                BuyerId = contract.BuyerId,
                SupplierId = contract.SupplierId,
                ImportContractId = contract.ImportContractId,
                Incoterm = contract.Incoterm,
                PaymentTerms = contract.PaymentTerms,
                ShipmentDatePlan = contract.ShipmentDatePlan,
                Note = contract.Note,
                CreatedBy = contract.CreatedBy,
                CreatedDate = contract.CreatedDate
            })
            .BuildQuery()
            + "\nRETURNING id;";
    }

    private static string BuildInsertAttachmentSql(ContractAttachment attachment)
    {
        IQueryBuilder<ContractAttachment, object> queryBuilder = new QueryBuilder<ContractAttachment, object>();
        return queryBuilder
            .Insert(() => new ContractAttachment
            {
                ContractId = attachment.ContractId,
                FileName = attachment.FileName,
                FileUrl = attachment.FileUrl,
                FileExtension = attachment.FileExtension,
                CreatedBy = attachment.CreatedBy,
                CreatedDate = attachment.CreatedDate
            })
            .BuildQuery();
    }

    private static string BuildInsertContractPackageSql(ContractPackage package)
    {
        IQueryBuilder<ContractPackageEntity, object> queryBuilder = new QueryBuilder<ContractPackageEntity, object>();
        return queryBuilder
            .Insert(() => new ContractPackageEntity
            {
                ContractId = package.ContractId,
                PackageId = package.PackageId,
                ProductId = package.ProductId,
                PackageQuantity = package.PackageQuantity,
                Note = package.Note,
                CreatedBy = package.CreatedBy,
                CreatedDate = package.CreatedDate
            })
            .BuildQuery()
            + "\nRETURNING id;";
    }

    private static string BuildInsertContractItemSql(ContractItem item)
    {
        IQueryBuilder<ContractItemEntity, object> queryBuilder = new QueryBuilder<ContractItemEntity, object>();
        return queryBuilder
            .Insert(() => new ContractItemEntity
            {
                ContractId = item.ContractId,
                ContractPackageId = item.ContractPackageId,
                PackageId = item.PackageId,
                ProductId = item.ProductId,
                SupplierId = item.SupplierId,
                Quantity = item.Quantity,
                ImportPrice = item.ImportPrice,
                SellPrice = item.SellPrice,
                TotalImportAmount = item.TotalImportAmount,
                TotalSellAmount = item.TotalSellAmount,
                CreatedBy = item.CreatedBy,
                CreatedDate = item.CreatedDate
            })
            .BuildQuery();
    }
}
