using Application.Packages.Repositories;
using Dapper;
using DomainPackage = Domain.Packages.Package;
using Infrastructure.Persistence.Db;
using Infrastructure.Persistence.Entities.Packages;
using Infrastructure.Persistence.Querying;
using Microsoft.Extensions.Logging;

namespace Infrastructure.Persistence.Repositories;

public class PackageRepository : IPackageRepository
{
    private readonly IDbConnectionFactory _connectionFactory;
    private readonly ILogger<PackageRepository> _logger;

    public PackageRepository(IDbConnectionFactory connectionFactory, ILogger<PackageRepository> logger)
    {
        _connectionFactory = connectionFactory;
        _logger = logger;
    }

    public async Task<DomainPackage?> GetByIdAsync(long packageId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<PackingList, object> queryBuilder = new QueryBuilder<PackingList, object>();
            var sql = queryBuilder
                .Select(p => new { p.Id, p.PackingListNo, p.PackageName, p.ProductQuantity, p.Length, p.Width, p.Height, p.Note, p.Delt, p.CreatedBy, p.CreatedDate, p.UpdatedBy, p.UpdatedDate })
                .Where(p => p.Id == packageId && (p.Delt != "Y" || p.Delt == null))
                .BuildQuery();

            _logger.LogInformation("GetById package SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var row = await connection.QueryFirstOrDefaultAsync<PackingList>(
                new CommandDefinition(sql, cancellationToken: cancellationToken));
            return row is null ? null : MapToDomain(row);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByIdAsync failed for package id: {Id}", packageId);
            throw;
        }
    }

    public async Task<DomainPackage?> GetByCodeAsync(string packageCode, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<PackingList, object> queryBuilder = new QueryBuilder<PackingList, object>();
            var sql = queryBuilder
                .Select(p => new { p.Id, p.PackingListNo, p.PackageName, p.ProductQuantity, p.Length, p.Width, p.Height, p.Note, p.Delt, p.CreatedBy, p.CreatedDate, p.UpdatedBy, p.UpdatedDate })
                .Where(p => p.PackingListNo == packageCode)
                .BuildQuery();

            _logger.LogInformation("GetByCode package SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var row = await connection.QueryFirstOrDefaultAsync<PackingList>(
                new CommandDefinition(sql, cancellationToken: cancellationToken));
            return row is null ? null : MapToDomain(row);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByCodeAsync failed for package code: {PackageCode}", packageCode);
            throw;
        }
    }

    public async Task<long> InsertAsync(DomainPackage package, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<PackingList, object> queryBuilder = new QueryBuilder<PackingList, object>();
            var sql = queryBuilder
                .Insert(() => new PackingList
                {
                    PackingListNo = package.PackageCode,
                    PackageName = package.PackageName,
                    ProductQuantity = package.ProductQuantity,
                    Length = package.Length,
                    Width = package.Width,
                    Height = package.Height,
                    Note = package.Note,
                    CreatedBy = package.CreatedBy,
                    CreatedDate = package.CreatedDate
                })
                .BuildQuery()
                + "\nRETURNING id;";

            _logger.LogInformation("Insert package SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            return await connection.ExecuteScalarAsync<long>(new CommandDefinition(sql, cancellationToken: cancellationToken));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertAsync failed for package code: {PackageCode}", package.PackageCode);
            throw;
        }
    }

    public async Task<bool> UpdateAsync(DomainPackage package, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<PackingList, object> queryBuilder = new QueryBuilder<PackingList, object>();
            var sql = queryBuilder
                .Update(() => new PackingList
                {
                    PackingListNo = package.PackageCode,
                    PackageName = package.PackageName,
                    ProductQuantity = package.ProductQuantity,
                    Length = package.Length,
                    Width = package.Width,
                    Height = package.Height,
                    Note = package.Note,
                    UpdatedBy = package.UpdatedBy,
                    UpdatedDate = package.UpdatedDate
                })
                .Where(p => p.Id == package.Id && (p.Delt != "Y" || p.Delt == null))
                .BuildQuery();

            _logger.LogInformation("Update package SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            return await connection.ExecuteAsync(new CommandDefinition(sql, cancellationToken: cancellationToken)) > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "UpdateAsync failed for package id: {Id}", package.Id);
            throw;
        }
    }

    public async Task<bool> DeleteAsync(long packageId, long currentUserId, DateTime updatedDate, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<PackingList, object> queryBuilder = new QueryBuilder<PackingList, object>();
            var sql = queryBuilder
                .Update(() => new PackingList
                {
                    Delt = "Y",
                    UpdatedBy = currentUserId,
                    UpdatedDate = updatedDate
                })
                .Where(p => p.Id == packageId && (p.Delt != "Y" || p.Delt == null))
                .BuildQuery();

            _logger.LogInformation("Delete package SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            return await connection.ExecuteAsync(new CommandDefinition(sql, cancellationToken: cancellationToken)) > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "DeleteAsync failed for package id: {Id}", packageId);
            throw;
        }
    }

    public async Task<PackageSearchResult> SearchAsync(PackageSearchCondition condition, CancellationToken cancellationToken = default)
    {
        const string whereClause = """
            (@KeywordPattern IS NULL
                OR t.PackingListNo ILIKE @KeywordPattern
                OR t.PackageName ILIKE @KeywordPattern
                OR COALESCE(t.Note, '') ILIKE @KeywordPattern)
            AND (t.Delt IS NULL OR t.Delt <> 'Y')
            """;

        IQueryBuilder<PackingList, object> countQueryBuilder = new QueryBuilder<PackingList, object>();
        var countSql = countQueryBuilder
            .SelectRaw("COUNT(*)")
            .WhereRaw(whereClause)
            .BuildQuery();

        IQueryBuilder<PackingList, object> dataQueryBuilder = new QueryBuilder<PackingList, object>();
        var dataSql = dataQueryBuilder
            .Select(p => new { p.Id, p.PackingListNo, p.PackageName, p.ProductQuantity, p.Length, p.Width, p.Height, p.Note, p.Delt, p.CreatedBy, p.CreatedDate, p.UpdatedBy, p.UpdatedDate })
            .WhereRaw(whereClause)
            .OrderByRaw("t.PackageName ASC, t.PackingListNo ASC")
            .Offset(condition.Offset)
            .Limit(condition.Limit)
            .BuildQuery();

        var parameters = new
        {
            KeywordPattern = string.IsNullOrWhiteSpace(condition.Keyword) ? null : $"%{condition.Keyword.Trim()}%",
            condition.Offset,
            condition.Limit
        };

        try
        {
            _logger.LogInformation("Search package SQL generated by IQueryBuilder: {Sql}", dataSql);
            _logger.LogInformation("Search package COUNT SQL generated by IQueryBuilder: {Sql}", countSql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var total = await connection.ExecuteScalarAsync<int>(new CommandDefinition(countSql, parameters, cancellationToken: cancellationToken));
            var rows = (await connection.QueryAsync<PackingList>(new CommandDefinition(dataSql, parameters, cancellationToken: cancellationToken))).ToList();

            return new PackageSearchResult
            {
                Items = rows.Select(MapToDomain).ToList(),
                Total = total
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "SearchAsync failed for packages.");
            throw;
        }
    }

    private static DomainPackage MapToDomain(PackingList entity)
    {
        return new DomainPackage
        {
            Id = entity.Id,
            PackageCode = entity.PackingListNo,
            PackageName = entity.PackageName ?? entity.PackingListNo,
            ProductQuantity = entity.ProductQuantity ?? 0,
            Length = entity.Length,
            Width = entity.Width,
            Height = entity.Height,
            Note = entity.Note,
            Delt = entity.Delt,
            CreatedBy = entity.CreatedBy,
            CreatedDate = entity.CreatedDate,
            UpdatedBy = entity.UpdatedBy,
            UpdatedDate = entity.UpdatedDate
        };
    }
}
