using Application.Partners.Repositories;
using Dapper;
using Domain.Partners;
using Infrastructure.Persistence.Db;
using Infrastructure.Persistence.Querying;
using Microsoft.Extensions.Logging;

namespace Infrastructure.Persistence.Repositories;

public class PartnerRepository : IPartnerRepository
{
    private readonly IDbConnectionFactory _connectionFactory;
    private readonly ILogger<PartnerRepository> _logger;

    public PartnerRepository(IDbConnectionFactory connectionFactory, ILogger<PartnerRepository> logger)
    {
        _connectionFactory = connectionFactory;
        _logger = logger;
    }

    public async Task<Partner?> GetByIdAsync(long partnerId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Partner, object> queryBuilder = new QueryBuilder<Partner, object>();
            var sql = queryBuilder
                .Select(p => new { p.Id, p.PartnerCode, p.PartnerName, p.PartnerType, p.Address, p.Phone, p.Email, p.IsActive, p.CreatedBy, p.CreatedDate, p.UpdatedBy, p.UpdatedDate })
                .Where(p => p.Id == partnerId)
                .BuildQuery();

            _logger.LogInformation("GetById partner SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            return await connection.QueryFirstOrDefaultAsync<Partner>(command);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByIdAsync failed for partner id: {Id}", partnerId);
            throw;
        }
    }

    public async Task<Partner?> GetByCodeAsync(string partnerCode, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Partner, object> queryBuilder = new QueryBuilder<Partner, object>();
            var sql = queryBuilder
                .Select(p => new { p.Id, p.PartnerCode, p.PartnerName, p.PartnerType, p.Address, p.Phone, p.Email, p.IsActive, p.CreatedBy, p.CreatedDate, p.UpdatedBy, p.UpdatedDate })
                .Where(p => p.PartnerCode == partnerCode)
                .BuildQuery();

            _logger.LogInformation("GetByCode partner SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            return await connection.QueryFirstOrDefaultAsync<Partner>(command);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByCodeAsync failed for partner code: {PartnerCode}", partnerCode);
            throw;
        }
    }

    public async Task<long> InsertAsync(Partner partner, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Partner, object> queryBuilder = new QueryBuilder<Partner, object>();
            var sql = queryBuilder
                .Insert(() => new Partner
                {
                    PartnerCode = partner.PartnerCode,
                    PartnerName = partner.PartnerName,
                    PartnerType = partner.PartnerType,
                    Address = partner.Address,
                    Phone = partner.Phone,
                    Email = partner.Email,
                    IsActive = partner.IsActive,
                    CreatedBy = partner.CreatedBy,
                    CreatedDate = partner.CreatedDate
                })
                .BuildQuery()
                + "\nRETURNING id;";

            _logger.LogInformation("Insert partner SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            return await connection.ExecuteScalarAsync<long>(command);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertAsync failed for partner code: {PartnerCode}", partner.PartnerCode);
            throw;
        }
    }

    public async Task<bool> UpdateAsync(Partner partner, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Partner, object> queryBuilder = new QueryBuilder<Partner, object>();
            var sql = queryBuilder
                .Update(() => new Partner
                {
                    PartnerCode = partner.PartnerCode,
                    PartnerName = partner.PartnerName,
                    PartnerType = partner.PartnerType,
                    Address = partner.Address,
                    Phone = partner.Phone,
                    Email = partner.Email,
                    IsActive = partner.IsActive,
                    UpdatedBy = partner.UpdatedBy,
                    UpdatedDate = partner.UpdatedDate
                })
                .Where(p => p.Id == partner.Id)
                .BuildQuery();

            _logger.LogInformation("Update partner SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            return await connection.ExecuteAsync(command) > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "UpdateAsync failed for partner id: {Id}", partner.Id);
            throw;
        }
    }

    public async Task<PartnerSearchResult> SearchAsync(PartnerSearchCondition condition, CancellationToken cancellationToken = default)
    {
        const string whereClause = """
            WHERE (@KeywordPattern IS NULL
                    OR partnercode ILIKE @KeywordPattern
                    OR partnername ILIKE @KeywordPattern
                    OR COALESCE(email, '') ILIKE @KeywordPattern
                    OR COALESCE(phone, '') ILIKE @KeywordPattern)
              AND (@PartnerType IS NULL OR partnertype = @PartnerType)
              AND (@IsActive IS NULL OR isactive = @IsActive)
            """;

        var dataWhereClause = whereClause.Trim().StartsWith("WHERE ", StringComparison.OrdinalIgnoreCase)
            ? whereClause.Trim()[6..]
            : whereClause;

        IQueryBuilder<Partner, object> countQueryBuilder = new QueryBuilder<Partner, object>();
        var countSql = countQueryBuilder
            .SelectRaw("COUNT(*)")
            .WhereRaw(dataWhereClause)
            .BuildQuery();

        IQueryBuilder<Partner, object> queryBuilder = new QueryBuilder<Partner, object>();
        var dataSql = queryBuilder
            .Select(p => new { p.Id, p.PartnerCode, p.PartnerName, p.PartnerType, p.Address, p.Phone, p.Email, p.IsActive, p.CreatedBy, p.CreatedDate, p.UpdatedBy, p.UpdatedDate })
            .WhereRaw(dataWhereClause)
            .OrderBy(p => p.PartnerName)
            .Offset(condition.Offset)
            .Limit(condition.Limit)
            .BuildQuery();

        var parameters = new
        {
            KeywordPattern = string.IsNullOrWhiteSpace(condition.Keyword) ? null : $"%{condition.Keyword.Trim()}%",
            condition.PartnerType,
            condition.IsActive,
            condition.Offset,
            condition.Limit
        };

        try
        {
            _logger.LogInformation("Search partner SQL generated by IQueryBuilder: {Sql}", dataSql);
            _logger.LogInformation("Search partner COUNT SQL generated by IQueryBuilder: {Sql}", countSql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var total = await connection.ExecuteScalarAsync<int>(new CommandDefinition(countSql, parameters, cancellationToken: cancellationToken));
            var items = (await connection.QueryAsync<Partner>(new CommandDefinition(dataSql, parameters, cancellationToken: cancellationToken))).ToList();

            return new PartnerSearchResult
            {
                Items = items,
                Total = total
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "SearchAsync failed for partners.");
            throw;
        }
    }
}
