using Application.Products.Repositories;
using Dapper;
using DomainProduct = Domain.Products.Product;
using Infrastructure.Persistence.Db;
using Infrastructure.Persistence.Entities.Products;
using Infrastructure.Persistence.Querying;
using Microsoft.Extensions.Logging;

namespace Infrastructure.Persistence.Repositories;

public class ProductRepository : IProductRepository
{
    private readonly IDbConnectionFactory _connectionFactory;
    private readonly ILogger<ProductRepository> _logger;

    public ProductRepository(IDbConnectionFactory connectionFactory, ILogger<ProductRepository> logger)
    {
        _connectionFactory = connectionFactory;
        _logger = logger;
    }

    public async Task<DomainProduct?> GetByIdAsync(long productId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Product, object> queryBuilder = new QueryBuilder<Product, object>();
            var sql = queryBuilder
                .Select(p => new { p.Id, p.ProductCode, p.ProductName, p.HsCode, p.UnitOfMeasure, p.Delt })
                .Where(p => p.Id == productId)
                .BuildQuery();

            _logger.LogInformation("GetById product SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var row = await connection.QueryFirstOrDefaultAsync<Product>(command);

            if (row is null || row.Delt == "Y")
            {
                return null;
            }

            return new DomainProduct
            {
                Id = row.Id,
                ProductCode = row.ProductCode,
                ProductName = row.ProductName,
                HsCode = row.HsCode,
                UnitOfMeasure = row.UnitOfMeasure
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByIdAsync failed for product id: {Id}", productId);
            throw;
        }
    }

    public async Task<long> InsertAsync(DomainProduct product, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Product, object> queryBuilder = new QueryBuilder<Product, object>();
            var sql = queryBuilder
                .Insert(() => new Product
                {
                    ProductCode = product.ProductCode,
                    ProductName = product.ProductName,
                    HsCode = product.HsCode,
                    UnitOfMeasure = product.UnitOfMeasure
                })
                .BuildQuery()
                + "\nRETURNING id;";

            _logger.LogInformation("Insert product SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            return await connection.ExecuteScalarAsync<long>(command);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertAsync failed for product code: {ProductCode}", product.ProductCode);
            throw;
        }
    }

    public async Task<bool> UpdateAsync(DomainProduct product, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Product, object> queryBuilder = new QueryBuilder<Product, object>();
            var sql = queryBuilder
                .Update(() => new Product
                {
                    ProductCode = product.ProductCode,
                    ProductName = product.ProductName,
                    HsCode = product.HsCode,
                    UnitOfMeasure = product.UnitOfMeasure
                })
                .Where(p => p.Id == product.Id)
                .BuildQuery();

            _logger.LogInformation("Update product SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "UpdateAsync failed for product id: {Id}", product.Id);
            throw;
        }
    }

    public async Task<bool> DeleteAsync(long productId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<Product, object> queryBuilder = new QueryBuilder<Product, object>();
            var sql = queryBuilder
                .Update(() => new Product
                {
                    Delt = "Y"
                })
                .Where(p => p.Id == productId)
                .BuildQuery();

            _logger.LogInformation("Delete product SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "DeleteAsync failed for product id: {Id}", productId);
            throw;
        }
    }

    public async Task<ProductSearchResult> SearchAsync(ProductSearchCondition condition, CancellationToken cancellationToken = default)
    {
        try
        {
            var productCode = condition.ProductCode?.Trim() ?? string.Empty;
            var productName = condition.ProductName?.Trim() ?? string.Empty;
            var hsCode = condition.HsCode?.Trim() ?? string.Empty;
            var unitOfMeasure = condition.UnitOfMeasure?.Trim() ?? string.Empty;

            IQueryBuilder<Product, object> queryBuilder = new QueryBuilder<Product, object>();
            queryBuilder
                .LeftJoin<ProductImage>((p, image) => p.Id == image.ProductId && image.IsDefault == "Y", "pi")
                .SelectRaw("t.Id, t.ProductCode, t.ProductName, t.HsCode, t.UnitOfMeasure, pi.ImageUrl")
                .OrderBy(p => p.ProductName)
                .Offset(condition.Offset)
                .Limit(condition.Limit);
            queryBuilder.Where(p =>
                (productCode == null || productCode == "" || (productCode != null && p.ProductCode.Contains(productCode)))
                && (productName == null || productName == "" || (productName != null && p.ProductName.Contains(productName)))
                && (hsCode == null || hsCode == "" || (hsCode != null && p.HsCode != null && p.HsCode.Contains(hsCode)))
                && (unitOfMeasure == null || unitOfMeasure == "" || (unitOfMeasure != null && p.UnitOfMeasure.Contains(unitOfMeasure))) && (p.Delt != "Y" || p.Delt == null)
            ).BuildQuery();

            var sql = queryBuilder.BuildQuery();

            IQueryBuilder<Product, object> countQueryBuilder = new QueryBuilder<Product, object>();
            countQueryBuilder.LeftJoin<ProductImage>((p, image) => p.Id == image.Id, "pi").SelectRaw("COUNT(*)");
            countQueryBuilder.Where(p =>
                (productCode == null || productCode == "" || (productCode != null && p.ProductCode.Contains(productCode)))
                && (productName == null || productName == "" || (productName != null && p.ProductName.Contains(productName)))
                && (hsCode == null || hsCode == "" || (hsCode != null && p.HsCode != null && p.HsCode.Contains(hsCode)))
                && (unitOfMeasure == null || unitOfMeasure == "" || (unitOfMeasure != null && p.UnitOfMeasure.Contains(unitOfMeasure))) && (p.Delt != "Y" || p.Delt == null)
            ).BuildQuery();

            var countSql = countQueryBuilder.BuildQuery();

            _logger.LogInformation("Search product SQL generated by IQueryBuilder: {Sql}", sql);
            _logger.LogInformation("Search product COUNT SQL generated by IQueryBuilder: {Sql}", countSql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var countCommand = new CommandDefinition(countSql, cancellationToken: cancellationToken);
            var total = await connection.ExecuteScalarAsync<int>(countCommand);

            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var items = (await connection.QueryAsync<ProductSearchData>(command)).ToList();

            return new ProductSearchResult
            {
                Items = items,
                Total = total
            };
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "SearchAsync failed.");
            throw;
        }
    }
}
