using Application.Products.Repositories;
using Dapper;
using DomainProductImage = Domain.Products.ProductImage;
using Infrastructure.Persistence.Db;
using Infrastructure.Persistence.Entities.Products;
using Infrastructure.Persistence.Querying;
using Microsoft.Extensions.Logging;

namespace Infrastructure.Persistence.Repositories;

public class ProductImageRepository : IProductImageRepository
{
    private readonly IDbConnectionFactory _connectionFactory;
    private readonly ILogger<ProductImageRepository> _logger;

    public ProductImageRepository(IDbConnectionFactory connectionFactory, ILogger<ProductImageRepository> logger)
    {
        _connectionFactory = connectionFactory;
        _logger = logger;
    }

    public async Task<DomainProductImage?> GetByIdAsync(long productImageId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<ProductImage, object> queryBuilder = new QueryBuilder<ProductImage, object>();
            var sql = queryBuilder
                .Select(p => new { p.Id, p.ProductId, p.ImageUrl, p.IsDefault, p.SortOrder })
                .Where(p => p.Id == productImageId)
                .OrderByRaw("t.IsDefault ASC")
                .BuildQuery();

            _logger.LogInformation("GetById product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var row = await connection.QueryFirstOrDefaultAsync<ProductImage>(command);
            return row is null ? null : MapToDomain(row);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByIdAsync failed for product image id: {ProductId}", productImageId);
            throw;
        }
    }

    public async Task<IReadOnlyList<DomainProductImage>> GetByProductIdAsync(long productId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<ProductImage, object> queryBuilder = new QueryBuilder<ProductImage, object>();
            var sql = queryBuilder
                .Select(p => new { p.Id, p.ProductId, p.ImageUrl, p.IsDefault, p.SortOrder })
                .Where(p => p.ProductId == productId)
                .OrderByRaw("t.IsDefault ASC")
                .BuildQuery();

            _logger.LogInformation("GetByProductId product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var rows = await connection.QueryAsync<ProductImage>(command);
            return rows.Select(MapToDomain).ToList();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByProductIdAsync failed for product id: {ProductId}", productId);
            throw;
        }
    }

    public async Task<long> InsertAsync(DomainProductImage productImage, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<ProductImage, object> queryBuilder = new QueryBuilder<ProductImage, object>();
            var sql = queryBuilder
                .Insert(() => new ProductImage
                {
                    ProductId = productImage.ProductId,
                    ImageUrl = productImage.ImageUrl,
                    IsDefault = productImage.IsDefault,
                    SortOrder = productImage.SortOrder
                })
                .BuildQuery()
                + "\nRETURNING id;";

            _logger.LogInformation("Insert product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            return await connection.ExecuteScalarAsync<long>(command);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertAsync failed for product id: {ProductId}", productImage.ProductId);
            throw;
        }
    }

    public async Task<bool> UpdateAsync(DomainProductImage productImage, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<ProductImage, object> queryBuilder = new QueryBuilder<ProductImage, object>();
            var sql = queryBuilder
                .Update(() => new ProductImage
                {
                    ProductId = productImage.ProductId,
                    ImageUrl = productImage.ImageUrl,
                    IsDefault = productImage.IsDefault,
                    SortOrder = productImage.SortOrder
                })
                .Where(p => p.Id == productImage.Id)
                .BuildQuery();

            _logger.LogInformation("Update product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "UpdateAsync failed for product image id: {ProductId}", productImage.Id);
            throw;
        }
    }

    public async Task<bool> DeleteAsync(long productImageId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<ProductImage, object> queryBuilder = new QueryBuilder<ProductImage, object>();
            var sql = queryBuilder
                .Delete()
                .Where(p => p.Id == productImageId)
                .BuildQuery();

            _logger.LogInformation("Delete product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "DeleteAsync failed for product image id: {ProductId}", productImageId);
            throw;
        }
    }

    private static DomainProductImage MapToDomain(ProductImage entity)
    {
        return new DomainProductImage
        {
            Id = entity.Id,
            ProductId = entity.ProductId,
            ImageUrl = entity.ImageUrl,
            IsDefault = entity.IsDefault,
            SortOrder = entity.SortOrder
        };
    }
}
