using Application.Users.Repositories;
using Dapper;
using Domain.Users;
using Infrastructure.Persistence.Db;
using Infrastructure.Persistence.Entities.Users;
using Infrastructure.Persistence.Querying;
using Microsoft.Extensions.Logging;

namespace Infrastructure.Persistence.Repositories;

public class UserRepository : IUserRepository
{
    private readonly IDbConnectionFactory _connectionFactory;
    private readonly ILogger<UserRepository> _logger;

    public UserRepository(IDbConnectionFactory connectionFactory, ILogger<UserRepository> logger)
    {
        _connectionFactory = connectionFactory;
        _logger = logger;
    }

    public async Task<User?> GetByIdAsync(long userId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<UserEntity, object> queryBuilder = new QueryBuilder<UserEntity, object>();
            var sql = queryBuilder
                .Select(u => new { u.Id, u.Username, u.Email, u.PasswordHash, u.FullName, u.ImageUrl, u.Role, u.RefreshToken, u.Delt, u.IsActive })
                .Where(u => u.Id == userId)
                .BuildQuery();

            sql = NormalizeSqlForUserTable(sql);
            _logger.LogInformation("GetById user SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var row = await connection.QueryFirstOrDefaultAsync<UserEntity>(command);

            return row is null || row.Delt == "Y"
                ? null
                : MapToDomain(row);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByIdAsync failed for user id: {Id}", userId);
            throw;
        }
    }

    public async Task<User?> GetByUsernameAsync(string username, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<UserEntity, object> queryBuilder = new QueryBuilder<UserEntity, object>();
            var sql = queryBuilder
                .Select(u => new { u.Id, u.Username, u.Email, u.PasswordHash, u.FullName, u.ImageUrl, u.Role, u.RefreshToken, u.Delt, u.IsActive })
                .Where(u => u.Username == username)
                .BuildQuery();

            sql = NormalizeSqlForUserTable(sql);
            _logger.LogInformation("GetByUsername user SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var row = await connection.QueryFirstOrDefaultAsync<UserEntity>(command);

            return row is null || row.Delt == "Y"
                ? null
                : MapToDomain(row);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByUsernameAsync failed for username: {Username}", username);
            throw;
        }
    }

    public async Task<User?> GetByEmailAsync(string email, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<UserEntity, object> queryBuilder = new QueryBuilder<UserEntity, object>();
            var sql = queryBuilder
                .Select(u => new { u.Id, u.Username, u.Email, u.PasswordHash, u.FullName, u.ImageUrl, u.Role, u.RefreshToken, u.Delt, u.IsActive })
                .Where(u => u.Email == email)
                .BuildQuery();

            sql = NormalizeSqlForUserTable(sql);
            _logger.LogInformation("GetByEmail user SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var row = await connection.QueryFirstOrDefaultAsync<UserEntity>(command);

            return row is null || row.Delt == "Y"
                ? null
                : MapToDomain(row);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByEmailAsync failed for email: {Email}", email);
            throw;
        }
    }

    public async Task<User?> GetByRefreshTokenAsync(string refreshToken, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<UserEntity, object> queryBuilder = new QueryBuilder<UserEntity, object>();
            var sql = queryBuilder
                .Select(u => new { u.Id, u.Username, u.Email, u.PasswordHash, u.FullName, u.ImageUrl, u.Role, u.RefreshToken, u.Delt, u.IsActive })
                .Where(u => u.RefreshToken == refreshToken)
                .BuildQuery();

            sql = NormalizeSqlForUserTable(sql);
            _logger.LogInformation("GetByRefreshToken user SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var row = await connection.QueryFirstOrDefaultAsync<UserEntity>(command);

            return row is null || row.Delt == "Y"
                ? null
                : MapToDomain(row);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByRefreshTokenAsync failed.");
            throw;
        }
    }

    public async Task<long> InsertAsync(User user, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<UserEntity, object> queryBuilder = new QueryBuilder<UserEntity, object>();
            var sql = queryBuilder
                .Insert(() => new UserEntity
                {
                    Username = user.Username,
                    Email = user.Email,
                    PasswordHash = user.PasswordHash,
                    FullName = user.FullName,
                    ImageUrl = user.ImageUrl,
                    Role = user.Role,
                    RefreshToken = user.RefreshToken,
                    Delt = "N",
                    IsActive = user.IsActive ? "Y" : "N"
                })
                .BuildQuery()
                + "\nRETURNING id;";

            sql = NormalizeSqlForUserTable(sql);
            _logger.LogInformation("Insert user SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            return await connection.ExecuteScalarAsync<long>(command);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertAsync failed for email: {Email}", user.Email);
            throw;
        }
    }

    public async Task<bool> UpdateAsync(User user, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<UserEntity, object> queryBuilder = new QueryBuilder<UserEntity, object>();
            var sql = queryBuilder
                .Update(() => new UserEntity
                {
                    Username = user.Username,
                    Email = user.Email,
                    PasswordHash = user.PasswordHash,
                    FullName = user.FullName,
                    ImageUrl = user.ImageUrl,
                    Role = user.Role,
                    RefreshToken = user.RefreshToken,
                    IsActive = user.IsActive ? "Y" : "N"
                })
                .Where(u => u.Id == user.Id)
                .BuildQuery();

            sql = NormalizeSqlForUserTable(sql);
            _logger.LogInformation("Update user SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "UpdateAsync failed for user id: {Id}", user.Id);
            throw;
        }
    }

    public async Task<bool> DeleteAsync(long userId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<UserEntity, object> queryBuilder = new QueryBuilder<UserEntity, object>();
            var sql = queryBuilder
                .Update(() => new UserEntity
                {
                    Delt = "Y",
                    IsActive = "N",
                    RefreshToken = null,
                })
                .Where(u => u.Id == userId && (u.Delt != "Y" || u.Delt == null))
                .BuildQuery();

            sql = NormalizeSqlForUserTable(sql);
            _logger.LogInformation("Delete user SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "DeleteAsync failed for user id: {Id}", userId);
            throw;
        }
    }

    public async Task<bool> ActivateAsync(long userId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<UserEntity, object> queryBuilder = new QueryBuilder<UserEntity, object>();
            var sql = queryBuilder
                .Update(() => new UserEntity
                {
                    IsActive = "Y"
                })
                .Where(u => u.Id == userId && (u.Delt != "Y" || u.Delt == null))
                .BuildQuery();

            sql = NormalizeSqlForUserTable(sql);
            _logger.LogInformation("Activate user SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "ActivateAsync failed for user id: {Id}", userId);
            throw;
        }
    }

    public async Task<bool> UpdateRefreshTokenAsync(long userId, string? refreshToken, DateTime? refreshTokenExpiresAtUtc, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<UserEntity, object> queryBuilder = new QueryBuilder<UserEntity, object>();
            var sql = queryBuilder
                .Update(() => new UserEntity
                {
                    RefreshToken = refreshToken,
                })
                .Where(u => u.Id == userId && (u.Delt != "Y" || u.Delt == null))
                .BuildQuery();

            sql = NormalizeSqlForUserTable(sql);
            _logger.LogInformation("Update refresh token SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _connectionFactory.CreateOpenConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "UpdateRefreshTokenAsync failed for user id: {Id}", userId);
            throw;
        }
    }

    private static string NormalizeSqlForUserTable(string sql)
    {
        return sql
            .Replace("INSERT INTO UserEntity", "INSERT INTO public.\"user\"")
            .Replace("UPDATE UserEntity t", "UPDATE public.\"user\" t")
            .Replace("DELETE FROM UserEntity t", "DELETE FROM public.\"user\" t")
            .Replace("FROM UserEntity t", "FROM public.\"user\" t");
    }

    private static User MapToDomain(UserEntity entity)
    {
        return new User
        {
            Id = entity.Id,
            Username = entity.Username,
            Email = entity.Email,
            PasswordHash = entity.PasswordHash,
            FullName = entity.FullName,
            ImageUrl = entity.ImageUrl,
            Role = entity.Role,
            RefreshToken = entity.RefreshToken,
            IsActive = string.Equals(entity.IsActive, "Y", StringComparison.OrdinalIgnoreCase)
        };
    }
}
