using Dapper;
using BussinessLayer.Products.Domain;
using BussinessLayer.Products.Repositories;
using DataManagement.DapperLib.Core;
using DataManagement.Helper;
using Microsoft.Extensions.Logging;

namespace DataAccessLayer.Repositories.ProductImageRepositories;

public class ProductImageRepository : IProductImageRepository
{
    private readonly IDbManagement _dbManagement;
    private readonly ILogger<ProductImageRepository> _logger;

    public ProductImageRepository(IDbManagement dbManagement, ILogger<ProductImageRepository> logger)
    {
        _dbManagement = dbManagement;
        _logger = logger;
    }

    public async Task<ProductImage?> GetByIdAsync(long productImageId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<ProductImageEntity, object> queryBuilder = new QueryBuilder<ProductImageEntity, object>();
            var sql = queryBuilder
                .Select(p => new { p.Id, p.ProductId, p.ImageUrl, p.IsDefault, p.SortOrder })
                .Where(p => p.Id == productImageId)
                .OrderBy(p => p.IsDefault)
                .BuildQuery();

            sql = NormalizeSqlForProductImageTable(sql);
            _logger.LogInformation("GetById product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _dbManagement.GetDbConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var row = await connection.QueryFirstOrDefaultAsync<ProductImageEntity>(command);
            return row is null ? null : MapToDto(row);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByIdAsync failed for product image id: {ProductId}", productImageId);
            throw;
        }
    }

    public async Task<IReadOnlyList<ProductImage>> GetByProductIdAsync(long productId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<ProductImageEntity, object> queryBuilder = new QueryBuilder<ProductImageEntity, object>();
            var sql = queryBuilder
                .Select(p => new { p.Id, p.ProductId, p.ImageUrl, p.IsDefault, p.SortOrder })
                .Where(p => p.ProductId == productId)
                .OrderBy(p => p.IsDefault)
                .BuildQuery();

            sql = NormalizeSqlForProductImageTable(sql);
            _logger.LogInformation("GetByProductId product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _dbManagement.GetDbConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var rows = await connection.QueryAsync<ProductImageEntity>(command);
            return rows.Select(MapToDto).ToList();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "GetByProductIdAsync failed for product id: {ProductId}", productId);
            throw;
        }
    }

    public async Task<long> InsertAsync(ProductImage productImage, CancellationToken cancellationToken = default)
    {
        try
        {
            var entity = new ProductImageEntity
            {
                ProductId = productImage.Id,
                ImageUrl = productImage.ImageUrl,
                IsDefault = productImage.IsDefault,
                SortOrder = productImage.SortOrder
            };

            IQueryBuilder<ProductImageEntity, object> queryBuilder = new QueryBuilder<ProductImageEntity, object>();
            var sql = queryBuilder
                .Insert(() => new ProductImageEntity
                {
                    ProductId = entity.ProductId,
                    ImageUrl = entity.ImageUrl,
                    IsDefault = entity.IsDefault,
                    SortOrder = entity.SortOrder
                })
                .BuildQuery();

            sql = NormalizeSqlForProductImageTable(sql) + "\nRETURNING id;";
            _logger.LogInformation("Insert product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _dbManagement.GetDbConnection();
            var command = new CommandDefinition(sql, entity, cancellationToken: cancellationToken);
            return await connection.ExecuteScalarAsync<long>(command);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "InsertAsync failed for product id: {ProductId}", productImage.Id);
            throw;
        }
    }

    public async Task<bool> UpdateAsync(ProductImage productImage, CancellationToken cancellationToken = default)
    {
        try
        {
            var entity = new ProductImageEntity
            {
                Id = productImage.ProductId,
                ProductId = productImage.Id,
                ImageUrl = productImage.ImageUrl,
                IsDefault = productImage.IsDefault,
                SortOrder = productImage.SortOrder
            };

            IQueryBuilder<ProductImageEntity, object> queryBuilder = new QueryBuilder<ProductImageEntity, object>();
            var sql = queryBuilder
                .Update(() => new ProductImageEntity
                {
                    ProductId = entity.ProductId,
                    ImageUrl = entity.ImageUrl,
                    IsDefault = entity.IsDefault,
                    SortOrder = entity.SortOrder
                })
                .Where(p => p.Id == entity.Id)
                .BuildQuery();

            sql = NormalizeSqlForProductImageTable(sql);
            _logger.LogInformation("Update product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _dbManagement.GetDbConnection();
            var command = new CommandDefinition(sql, entity, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "UpdateAsync failed for product image id: {ProductId}", productImage.ProductId);
            throw;
        }
    }

    public async Task<bool> DeleteAsync(long productImageId, CancellationToken cancellationToken = default)
    {
        try
        {
            IQueryBuilder<ProductImageEntity, object> queryBuilder = new QueryBuilder<ProductImageEntity, object>();
            var sql = queryBuilder
                .Delete()
                .Where(p => p.Id == productImageId)
                .BuildQuery();

            sql = NormalizeSqlForProductImageTable(sql);
            _logger.LogInformation("Delete product image SQL generated by IQueryBuilder: {Sql}", sql);

            using var connection = _dbManagement.GetDbConnection();
            var command = new CommandDefinition(sql, cancellationToken: cancellationToken);
            var affectedRows = await connection.ExecuteAsync(command);
            return affectedRows > 0;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "DeleteAsync failed for product image id: {ProductId}", productImageId);
            throw;
        }
    }

    private static string NormalizeSqlForProductImageTable(string sql)
    {
        return sql
            .Replace("INSERT INTO ProductImageEntity", "INSERT INTO productimage")
            .Replace("UPDATE ProductImageEntity t", "UPDATE productimage t")
            .Replace("DELETE FROM ProductImageEntity t", "DELETE FROM productimage t")
            .Replace("FROM ProductImageEntity t", "FROM productimage t");
    }

    private static ProductImage MapToDto(ProductImageEntity entity)
    {
        return new ProductImage
        {
            ProductId = entity.Id,
            Id = entity.ProductId,
            ImageUrl = entity.ImageUrl,
            IsDefault = entity.IsDefault  ,
            SortOrder = entity.SortOrder,
            Delt = "N"
        };
    }

    private static bool ParseIsDefault(string? isMain)
    {
        if (string.IsNullOrWhiteSpace(isMain))
        {
            return false;
        }

        var value = isMain.Trim().ToUpperInvariant();
        return value is "Y" or "1" or "TRUE" or "T";
    }

    private sealed class ProductImageEntity
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public string ImageUrl { get; set; } = string.Empty;
        public string? IsDefault { get; set; }
        public int SortOrder { get; set; }
    }
}
